[BACKLOG-36890] Keyboard Navigation (A) for Layout
pentaho/pentaho-platform-plugin-common-ui pull request #1613
Opened 2023-02-06 06:21 UTC by hv-vamsi

2023-02-06 15:20 UTC, hv-vamsi commented
@pentaho/wcag, Please review

2023-02-06 15:20 UTC, dcleao requested changes
All fine except formatting.

2023-02-06 15:20 UTC, dcleao commented on impl/client/src/main/javascript/web/dojo/pentaho/common/propertiesPanel/Panel.js
> +		on(this.domNode, "keypress", lang.hitch(this, "onContextMenu")),
Indentation is off.

2023-02-06 15:24 UTC, hv-vamsi commented on impl/client/src/main/javascript/web/dojo/pentaho/common/propertiesPanel/Panel.js
> +		on(this.domNode, "keypress", lang.hitch(this, "onContextMenu")),
addressed

2023-02-07 05:07 UTC, phalguni-a approved these changes

2023-02-07 05:08 UTC, merged