[BACKLOG-36843]-Accessibility-Buttons and Keycodes
pentaho/pentaho-platform-plugin-common-ui pull request #1619
Opened 2023-02-15 11:42 UTC by phalguni-a

@pentaho/wcag , please review

2023-02-15 16:05 UTC, dcleao requested changes

2023-02-15 16:05 UTC, dcleao commented on impl/client/src/main/javascript/web/util/_a11y.js
> +  var _isToggleButton = false;
This module variable is not the best way to solve the issue. There are simpler, safer, cleaner solutions.

For example, create an internal function which receives a parameter that indicates the type of button:
```js
function makeAccessibleButton(elem, isToggleButton) {
   // ...
}

return {
    keyCodes: keyCodes,

    makeAccessibleActionButton: function(elem) { 
       makeAccessibleButton(elem, false);
    },

    makeAccessibleToggleButton: function(elem) { 
       makeAccessibleButton(elem, true);
    }
  };
```

2023-02-15 20:02 UTC, dcleao commented on impl/client/src/main/javascript/web/util/_a11y.js
> +    function actionButtonKeydownHandler(event) {
Note suggested character case of "KeyDown": `actionButtonKeyDownHandler`.

2023-02-15 20:02 UTC, dcleao commented on impl/client/src/main/javascript/web/util/_a11y.js
> +    function actionButtonKeyupHandler(event) {
Note suggested character case of "KeyUp": `actionButtonKeyUpHandler`.

2023-02-16 06:56 UTC, phalguni-a commented
@dcleao , Addressed the required. Can you please review now.

2023-02-16 12:32 UTC, hv-vamsi approved these changes

2023-02-16 15:42 UTC, ddiroma approved these changes

2023-02-16 15:53 UTC, merged