[BACKLOG-37783] Added keyboard Navigation and focus visibility for top part of Sidebar and in Formatting panel-> tabs for color palette
pentaho/pentaho-platform-plugin-common-ui pull request #1655
Opened 2023-06-01 15:00 UTC by kdarshana12

@pentaho/wcag , please review.

2023-06-01 15:17 UTC, kdarshana12 commented on impl/client/src/main/javascript/web/dojo/pentaho/common/TabSet.js
> +                if(tabIdx === idx) {
Does 'selectedTab' as variable name work?

2023-06-01 16:31 UTC, dcleao requested changes

2023-06-01 16:55 UTC, dcleao approved these changes

2023-06-05 04:58 UTC, phalguni-a approved these changes

2023-06-05 07:00 UTC, merged