[BACKLOG-38666] Added Keyboard navigation for previous-next page buttons - Pentaho report viewer
pentaho/pentaho-platform-plugin-common-ui pull request #1698
Opened 2023-10-12 15:58 UTC by kdarshana12

@pentaho/wcag . Please review
Addressing some comments from https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1679

2023-10-23 11:18 UTC, dcleao requested changes

2023-10-23 11:18 UTC, dcleao commented on impl/client/src/main/javascript/web/dojo/pentaho/common/PageControl.js
> +      this._updatePageButtonState();
Could this not be a call to `this._setPageNumberInput(this.pageNumber)`?

2023-10-23 11:18 UTC, dcleao commented on impl/client/src/main/javascript/web/dojo/dijit/themes/pentaho/PageControl.css
> +  padding: 1px 0px 0px 2px;
Missing new line at end of file.

![IntelliJ Ensure New Line At EOF](https://github.com/pentaho/pentaho-platform-plugin-common-ui/assets/284983/eda16a0a-ea33-45bb-8bac-e9c2bc932b99)

2023-10-30 08:35 UTC, kdarshana12 commented
Merge with https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/812

2023-10-31 10:28 UTC, dcleao approved these changes

2023-10-31 10:34 UTC, hv-vamsi approved these changes

2023-10-31 11:24 UTC, merged