[BACKLOG-39166] Ensure Page Setup Dialog Buttons are Keyboard Navigable
pentaho/pentaho-platform-plugin-common-ui pull request #1719
Opened 2023-11-13 21:49 UTC by singletonc

Move buttons to correct div location to be navigable via tab

2023-11-14 12:48 UTC, dcleao approved these changes

2023-11-14 12:50 UTC, AAravind27 approved these changes

2023-11-14 13:08 UTC, dcleao commented
Converted to draft temporarilly, as I am now unsure this is the right approach.

2023-11-14 13:28 UTC, dcleao requested changes

2023-11-15 14:30 UTC, dcleao approved these changes

2023-11-15 14:33 UTC, AAravind27 approved these changes

2023-11-15 15:05 UTC, merged