[BACKLOG-40489] Error when accessing browse files with a user with sp…
pentaho/pentaho-platform-plugin-common-ui pull request #1762
Opened 2024-04-24 21:08 UTC by singletonc

…ecial characteres (that used to work before)

- Add new en/decode functions for generic file paths to address handling of "~" in file paths

2024-04-24 21:18 UTC, buildguy commented
### :white_check_mark: Build finished in 10m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
:ok_hand: All tests passed!
 
Tests run: **5240**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui/job/PR-1762/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-25 18:06 UTC, NJtwentyone commented on impl/client/src/main/javascript/web/util/URLEncoder.js
> +        .replaceAll("~", "\t")
unit tests for the new function `Encoder.encodeGenericFilePath `. There should be js examples within the Pentaho code base.

2024-04-25 18:07 UTC, NJtwentyone requested changes
unit tests if possible and feasible - https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1762/files#r1579918221

based off slack conversation: https://hitachivantara-eng.slack.com/archives/C01HJ874L8Z/p1714064875038819?thread_ts=1714059884.952579&cid=C01HJ874L8Z

2024-04-25 22:41 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-25 22:41 UTC, buildguy commented
### :white_check_mark: Build finished in 8m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
:ok_hand: All tests passed!
 
Tests run: **5241**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui/job/PR-1762/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-26 10:09 UTC, dcleao approved these changes

2024-04-29 14:43 UTC, NJtwentyone commented on impl/client/src/test/javascript/util/URLEncoder.spec.js
> +    it("should encode generic file path characters", function() {
good. adding unit tests.

2024-04-29 14:43 UTC, NJtwentyone approved these changes

2024-04-29 14:43 UTC, merged