[BACKLOG-40489] Error when accessing browse files with a user with special characters
pentaho/pentaho-platform-plugin-common-ui pull request #1765
Opened 2024-05-09 22:45 UTC by singletonc

- Overload encode function to allow for disabling of double-encoding slashes, as this is not needed in all cases.

2024-05-09 22:57 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-05-09 22:57 UTC, buildguy commented
### :warning: Build finished in 11m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>.URL Encoder.URL Encoder should handle reserved URI strings</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>.URL Encoder.URL Encoder should handle multiple occurrences of slashes</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5241**, Failures: **2**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui/job/PR-1765/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-05-10 11:07 UTC, dcleao commented on impl/client/src/main/javascript/web/util/URLEncoder.js
> +  Encoder.encode = function(str, args, queryObj){
In JavaScript, we cannot create overloads in this way. The second overload function, below, simply overwrites the first one here set on the `Encoder.encode` property. In JavaScript, functions are values.

The alternative pattern is then to have all needed parameters in a function and to explicitly check if these were specified by comparing them to `undefined`, or, in the case of a boolean property, more leniently checking if it is _nully,_ `== null` (which matches both `null` and `undefined`).

The way this is proposed, the default value of `doubleEncodeSlashes` is, in practice, inadvertently changed to `false`.

2024-05-10 11:15 UTC, dcleao commented on impl/client/src/main/javascript/web/util/URLEncoder.js
> +        }
The double encoding `doubleEncodeSlashes` parameter should only affect the execution of this block, and not of the entire loop, which includes the necessary `encodeURIComponent` call.

2024-05-10 12:46 UTC, soagarwal1 approved these changes

2024-05-10 13:32 UTC, NJtwentyone commented on impl/client/src/main/javascript/web/util/URLEncoder.js
> +    }
update `URLEncoder.spec.js`

you previous made changes to https://github.com/pentaho/pentaho-platform-plugin-common-ui/blob/master/impl/client/src/test/javascript/util/URLEncoder.spec.js

If you had to make changes to the source code, then shouldn't you have to make changes to the automated test code as well?

2024-05-10 13:33 UTC, NJtwentyone requested changes
update automated test class see comment - https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1765/files#r1596759242

2024-05-10 15:16 UTC, closed without merging