[BACKLOG-41091] Decode PVFS File Paths: Scheduler Perspective + Browse Perspective missed case
pentaho/pentaho-platform-plugin-common-ui pull request #1777
Opened 2024-06-27 18:16 UTC by singletonc

- Move decode logic into URLEncoder.js for general use in project

2024-06-27 18:26 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-06-27 18:26 UTC, buildguy commented
### :white_check_mark: Build finished in 9m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
:ok_hand: All tests passed!
 
Tests run: **5241**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui/job/PR-1777/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-06-27 18:30 UTC, rmansoor approved these changes

2024-07-01 10:51 UTC, dcleao requested changes

2024-07-01 10:51 UTC, dcleao commented on impl/client/src/main/javascript/web/util/URLEncoder.js
> +  }
Not needed in solution proposed in: https://github.com/pentaho/pentaho-platform/pull/5647#pullrequestreview-2151052689.

2024-07-03 15:37 UTC, closed without merging

2024-07-03 15:37 UTC, singletonc commented
Closing in favor of new PR Set:
[pentaho/pentaho-commons-gwt-modules#1042](https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1042)
[pentaho/pentaho-platform#5652](https://github.com/pentaho/pentaho-platform/pull/5652)
[pentaho/pentaho-scheduler-plugin#187](https://github.com/pentaho/pentaho-scheduler-plugin/pull/187)
[pentaho/pentaho-scheduler-plugin-ee#256](https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/256)