fix: update dojo to v1.17.3 [PPP-4824]
pentaho/pentaho-platform-plugin-common-ui pull request #1788
Opened 2024-09-04 18:03 UTC by davidmsantos90

Update from dojo **v1.9.2** to **v1.17.3**

@pentaho/millenniumfalcon please review

### Overrides
| File | Source update in 1.17 | Keep Override |  description  |
| :--- | :--------------------: | :-------------: | --- |
| dijit/_CssStateMixin.js | ❌ | ✅ |  | 
| dijit/_HasDropDown.js | ✅ | ✅ |  | 
| dijit/_PaletteMixin.js | ❌ | ✅ |  | 
| dijit/Dialog.js | ✅ | ✅ |  | 
| dijit/Menu.js | ✅ | ✅ |  | 
|  |  |  |
| dojo/_base/config.js | ✅ | ✅ |  |
| dojo/_base/kernel.js | ✅ | ❌ | fixed: global properly defined |
| dojo/request/default.js | ✅ | ✅ |  |
| dojo/selector/_loader.js | ✅ | ❌ | fixed: r.js build |
| dojo/store/JsonRest.js | ✅ | ❌ | override was file from v1.17.3 |
| dojo/store/Memory.js | ✅ | ❌ | fixed: add/put methods use `options` arg |
| dojo/dom-geometry.js | ✅ | ❌ | fixed: return empty rectangle on error |
| dojo/dom-prop.js | ✅ | ✅ |  |
| dojo/i18n.js | ✅ | ✅ |  |
| dojo/on.js | ✅ | ❌ | override was from v1.9.6 |
|  |  |  |
| dojox/grid/_FocusManager.js | ❌ | ❌ | only override was `array.some` instead of `dojo.some` |
| dojox/grid/_Scroller.js | ❌ | ❌ | only override was `array.forEach` instead of `dojo.forEach` |
| dojox/grid/_View.js | ✅ | ✅ | remove "dojo" require |
| dojox/grid/Selection.js | ❌ | ✅ | force ctrl as copy key |
| dojox/json/ref.js | ✅ | ✅ | remove "dojox" require |
| dojox/json/schema.js | ❌ | ✅ | remove "dojox" require |
| dojox/layout/ReziseHandle.js | ✅ | ❌ | only override was `declare` instead of `dojo.declare` |
| dojox/rpc/JsonRest.js | ❌ | ✅ |  |
| dojox/rpc/Rest.js | ❌ | ✅ |  |
| dojox/storage/_common.js | ❌ | ✅ | original source is not AMD |
| dojox/storage/LocalStorageProvider.js | ✅ | ❌ | is AMD in new version, override not required |
| dojox/storage/manager.js | ✅ | ❌ | is AMD in new version, override not required |
| dojox/storage/Provider.js | ✅ | ❌ | is AMD in new version, override not required |
| dojox/storage/WhatWGStorageProvider.js | ❌ | ❌ | override is equal to original source |
| dojox/xml/parser.js | ❌ | ❌ | just defining dojox if not defined |
| dojox/storage.js | ❌ | ❌ | override is equal to original source |

2024-09-04 18:15 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-09-04 18:15 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
:ok_hand: All tests passed!
 
Tests run: **5198**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui/job/PR-1788/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-09-04 18:33 UTC, buildguy commented
### :x: Build failed in 40s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-09-05 10:25 UTC, mbrasil approved these changes

2024-09-09 16:50 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-09-09 16:50 UTC, buildguy commented
### :white_check_mark: Build finished in 13m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
:ok_hand: All tests passed!
 
Tests run: **5198**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/common-ui/job/PR-1788/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-09-10 11:51 UTC, dcleao requested changes

2024-09-10 11:51 UTC, dcleao commented on pom.xml
> +        <groupId>org.dojotoolkit</groupId>
Still needed?

2024-09-10 11:54 UTC, dcleao commented on pom.xml
> -    <dojo.version>1.9.2</dojo.version>
Nice improvement, moving to parent pom!

2024-09-10 16:40 UTC, dcleao approved these changes
💯 💯 !

2024-09-10 17:30 UTC, merged

2024-09-10 17:42 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>